#!/bin/bash
# AfterInstall - pull Docker images from ECR after files are copied.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

log_info "AfterInstall hook started"

ENVIRONMENT=$(detect_environment)
log_info "Detected environment: $ENVIRONMENT"

APP_DIR=$(get_app_directory "$ENVIRONMENT")
log_info "Application directory: $APP_DIR"

# -- Install ECR credential refresh timer (ALL nodes) ------------------------
# This must run on every node, not just the leader, because leadership can
# move.  The script itself detects leadership at runtime: it refreshes the
# local ECR login on every node and only pushes credentials into the Swarm
# raft store when it runs on the current leader.

SCRIPT_PATH="$APP_DIR/deploy/codedeploy/ecr-refresh-and-cleanup.sh"
TIMER_SRC="$APP_DIR/deploy/codedeploy/ecr-refresh.timer"
SERVICE_SRC="$APP_DIR/deploy/codedeploy/ecr-refresh.service"

if [ -f "$SERVICE_SRC" ]; then
    sed -i "s|ExecStart=.*|ExecStart=${SCRIPT_PATH}|" "$SERVICE_SRC"
fi

if [ -f "$TIMER_SRC" ] && [ -f "$SERVICE_SRC" ]; then
    log_info "Installing ECR credential refresh systemd timer..."
    cp "$SERVICE_SRC" /etc/systemd/system/ecr-refresh.service
    cp "$TIMER_SRC" /etc/systemd/system/ecr-refresh.timer
    systemctl daemon-reload
    systemctl enable --now ecr-refresh.timer 2>/dev/null || true
    log_success "ECR refresh timer installed and enabled"
fi

if ! is_swarm_leader; then
    log_info "Non-leader node -- skipping image pull"
    log_success "AfterInstall hook completed (non-leader node)"
    exit 0
fi

cd "$APP_DIR"

# -- Install environment file ------------------------------------------------

# The deployment package includes staging.env or prod.env generated by the
# GitHub Actions workflow.  Copy it to .env so docker-compose picks it up.

ENV_FILE=$(get_env_file "$ENVIRONMENT")
log_info "Target env file: $ENV_FILE"

SHIPPED_ENV=""
if [ "$ENVIRONMENT" = "staging" ]; then
    SHIPPED_ENV="$APP_DIR/staging.env"
elif [ "$ENVIRONMENT" = "production" ]; then
    SHIPPED_ENV="$APP_DIR/prod.env"
fi

if [ -n "$SHIPPED_ENV" ] && [ -f "$SHIPPED_ENV" ]; then
    log_info "Installing shipped env file: $SHIPPED_ENV -> $ENV_FILE"
    cp "$SHIPPED_ENV" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
elif [ -f "$ENV_FILE" ]; then
    log_warning "No shipped env file found; keeping existing $ENV_FILE"
else
    log_error "No environment file found — deployment cannot continue."
    log_error "Expected: $SHIPPED_ENV"
    ls -la "$APP_DIR"/*.env 2>/dev/null || echo "(no .env files in $APP_DIR)"
    exit 1
fi

# -- Load environment --------------------------------------------------------

log_info "Loading environment from $ENV_FILE"
if ! safe_source_env "$ENV_FILE"; then
    log_error "Failed to load environment file: $ENV_FILE"
    exit 1
fi

# -- Verify ECR configuration ------------------------------------------------

if [ -z "$ECR_REGISTRY" ] || [ -z "$WEBAPP_IMAGE" ]; then
    log_error "ECR images not configured!"
    log_error "Required: ECR_REGISTRY, WEBAPP_IMAGE"
    log_error "ECR_REGISTRY=$ECR_REGISTRY"
    log_error "WEBAPP_IMAGE=$WEBAPP_IMAGE"
    exit 1
fi

log_info "ECR Registry: $ECR_REGISTRY"
log_info "Webapp Image: $WEBAPP_IMAGE"

# -- Pull images --------------------------------------------------------------

ecr_login "$ECR_REGISTRY" || { log_error "ECR login failed"; exit 1; }

log_info "Pulling webapp image: $WEBAPP_IMAGE"
if ! docker pull "$WEBAPP_IMAGE"; then
    log_error "Failed to pull webapp image: $WEBAPP_IMAGE"
    exit 1
fi
log_success "Webapp image pulled successfully"

# Tag for compose usage
docker tag "$WEBAPP_IMAGE" "${ECR_REGISTRY}/avoided-emissions-webapp:${ENVIRONMENT}-latest"
docker tag "$WEBAPP_IMAGE" "${ECR_REGISTRY}/avoided-emissions-webapp:latest"

log_info "Image tags:"
docker images --filter "reference=*/avoided-emissions-webapp" \
    --format "table {{.Repository}}:{{.Tag}}\t{{.ID}}\t{{.Size}}"

# -- Permissions --------------------------------------------------------------

chown -R ubuntu:ubuntu "$APP_DIR"
chmod +x "$APP_DIR/deploy/codedeploy/"*.sh 2>/dev/null || true

# -- Deployment metadata ------------------------------------------------------

DEPLOY_TAG=$(echo "$WEBAPP_IMAGE" | sed 's/.*://')
echo "$DEPLOY_TAG" > "$APP_DIR/.deploy_tag"
date -u +"%Y-%m-%d %H:%M:%S UTC" > "$APP_DIR/.deploy_timestamp"
log_info "Saved deployment tag: $DEPLOY_TAG"

log_success "AfterInstall hook completed"
exit 0
